#!/usr/bin/env python3
"""Build every per-object asset our recognizer needs for the 21 YCB-V objects
(after the 42-view templates were rendered by render_templates_bproc.py).

  1. recognizer config  WORK/ycbv_objects.yaml  (defaults copied verbatim from the deployed
     configs/yolo_ism_objects.yaml; per object: prompt, template dir, caches, hue correction 0)
  2. HSV template caches  (the repo tool tools/build_hsv_template_cache.py --config <ours>)
  3. DINOv2 ViT-S cls / masked-appearance caches (yolo_ism_object_n.prepare_objects)
  4. PEM assets in a stand-in repo dir WORK/core_repo/assets:
       model_points/<name>.npy  8192 CAD surface samples (mm), as the deployed assets
       pem_templates/<name>.pt  {tp, tf} = PEM get_obj_feats over the 42 templates
                                 (run_inference_custom.get_templates), + tc point colours
                                 (tools/add_template_colors.build)
       clip -> symlink to the repo's assets/clip (YOLO-World text encoder)

    python build_assets.py [--objs 1,2,...] [--force]
"""
import argparse
import copy
import os
import subprocess
import sys

import numpy as np
import torch
import trimesh
import yaml

import paths as P


def write_config(oids):
    base = yaml.safe_load(open(P.BASE_CFG))
    d = copy.deepcopy(base["defaults"])
    for k in ("weights", "seg_weights"):
        if not os.path.isabs(d[k]):
            d[k] = str(P.SR / d[k])
    objs = []
    for oid in oids:
        nm = P.obj_name(oid)
        objs.append({"name": nm, "yolo_prompt": P.PROMPTS[oid - 1], "object_id": P.YCB_NAMES[oid - 1],
                     "template_dir": str(P.TEMPLATES / f"obj_{oid:06d}" / "templates"),
                     "cad_ply": str(P.YCBV / "models" / f"obj_{oid:06d}.ply"),
                     "cls_cache": str(P.FEATURES / f"{nm}_cls.pt"),
                     "appe_cache": str(P.FEATURES / f"{nm}_appe.pt"),
                     "hsv_cache": str(P.FEATURES / f"{nm}_hsv.npz"),
                     "hsv_hue_correction_ocv": 0, "enabled": True})
    P.WORK.mkdir(parents=True, exist_ok=True)
    with open(P.OURS_CFG, "w") as f:
        f.write("# generated by paper_etrij_261003/src/ycbv/build_assets.py; defaults = deployed "
                "configs/yolo_ism_objects.yaml defaults (weights paths made absolute)\n")
        yaml.safe_dump({"defaults": d, "objects": objs}, f, sort_keys=False, allow_unicode=True)
    print("config ->", P.OURS_CFG)


def dinov2_caches():
    sys.path.insert(0, str(P.SR))
    import yolo_ism as yi
    import yolo_ism_object_n as o_n
    defaults, objs = o_n.load_config(str(P.OURS_CFG))
    model = yi.build_dinov2(defaults.get("dinov2_checkpoint") or yi.DEFAULT_DINOV2_CKPT, "cuda:0")
    o_n.prepare_objects(objs, model, "cuda:0", rebuild=False)


def pem_assets(oids, force):
    a = P.CORE_REPO / "assets"
    (a / "model_points").mkdir(parents=True, exist_ok=True)
    (a / "pem_templates").mkdir(parents=True, exist_ok=True)
    if not (a / "clip").exists():
        os.symlink(P.SR / "assets" / "clip", a / "clip")
    pem_dir = P.SR / "sam6d_master/SAM-6D/Pose_Estimation_Model"
    cwd = os.getcwd(); os.chdir(pem_dir)
    for sub in ("provider", "utils", "model", "model/pointnet2"):
        sys.path.append(str(pem_dir / sub))
    sys.path.insert(0, str(pem_dir))
    import gorilla
    import importlib
    import run_inference_custom as ric
    cfg = gorilla.Config.fromfile(str(pem_dir / "config/base.yaml"))
    net = importlib.import_module("pose_estimation_model").Net(cfg.model).to("cuda:0").eval()
    gorilla.solver.load_checkpoint(model=net, filename=str(P.PEM_CKPT))
    os.chdir(cwd)
    sys.path.insert(0, str(P.SR / "tools"))
    import add_template_colors as atc
    atc.TEM_DIR = str(a / "pem_templates")
    for oid in oids:
        nm = P.obj_name(oid)
        mp, tp_path = a / "model_points" / f"{nm}.npy", a / "pem_templates" / f"{nm}.pt"
        if force or not mp.exists():
            mesh = trimesh.load(str(P.YCBV / "models" / f"obj_{oid:06d}.ply"), force="mesh")
            pts = trimesh.sample.sample_surface(mesh, 8192, seed=oid)[0].astype(np.float32)
            np.save(mp, pts)
        if force or not tp_path.exists():
            tdir = str(P.TEMPLATES / f"obj_{oid:06d}" / "templates")
            np.random.seed(oid)
            T, Pt, C = ric.get_templates(tdir, cfg.test_dataset)
            with torch.inference_mode():
                tp, tf = net.feature_extraction.get_obj_feats(T, Pt, C)
            torch.save({"tp": tp.cpu(), "tf": tf.cpu(), "tdir": tdir}, tp_path)
            s = atc.build(nm, 2.0 / 1000.0, torch.device("cuda:0"), True)
            print(nm, "pem template", tuple(tp.shape), tuple(tf.shape), "tc", s)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--objs", default=",".join(str(i) for i in range(1, 22)))
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--skip", default="", help="comma list of steps to skip: config,hsv,dino,pem")
    a = ap.parse_args()
    oids = [int(x) for x in a.objs.split(",")]
    skip = set(a.skip.split(","))
    if "config" not in skip:
        write_config(list(range(1, 22)))
    if "hsv" not in skip:
        subprocess.run([sys.executable, str(P.SR / "tools/build_hsv_template_cache.py"),
                        "--config", str(P.OURS_CFG)] + (["--force"] if a.force else []),
                       check=True, cwd=str(P.SR))
    if "dino" not in skip:
        dinov2_caches()
    if "pem" not in skip:
        pem_assets(oids, a.force)


if __name__ == "__main__":
    main()
